### ISSUE TITLE
Crope Image (one the left) is not updated.

### ISSUE THREAD

**Issue by dmatrak** [MiroJ/AvatarUpload#2]
I would like to report a bug that I found. Crop image  (on the left) is not updated, if all the elements are not hidden and the user selects different images before save. Do you have any solution for this?

**Comment by MiroJ** [comment]
The easiest I can think of is to hide make the  JS reload the page so the uploading process restarts. Otherwise, you will need to improve the JS logic based on your workflow. The code is provided as concept.
