### ISSUE TITLE
Image preview and crop editor image won't show in Firefox after upload selection

### ISSUE THREAD

**Issue by mdnorwood** [MiroJ/AvatarUpload#3]
Works great in Chrome, IE and Edge but after uploading the image in Firefox, the small preview image and the crop editor image never show up for me. The save button does show up but after selecting I'm getting: 

"Unable to upload file.
ERRORINFO: Value must be greater than or equal to 0.
Parameter name: bottom"

Again, works great in all other browsers with both the original source code version I tried and with it implemented into a custom project, it's just Firefox where I'm finding the issue in both.

Other than that, great job to the authors!

**Comment by mistertommat** [comment]
Same issue with Firefox. Anyone else noticed this / has a fix please?

The 'div class="jcrop-holder"....' is not rendered at all in Firefox when selecting an image. If I debug through the site.avatar.js file after selecting an image, the 'div class="jcrop-holder"....' is rendered but the image is still not shown.

Any pointers to how this can be solved?

**Comment by ryzam** [comment]
You need to modify AvatarController that return image path after success upload

return Json(new { success = true, fileName = webPath.Replace("\","/") });

**Comment by MiroJ** [comment]
New code from mistertommat branch is pulled in now.
