### ISSUE TITLE
Fails for widths/heights above 100px

### ISSUE THREAD

**Issue by danieldiazastudillo** [MiroJ/AvatarUpload#6]
Can't manage to work with sizes above 100 pixels, even without resizing temporary avatar. What can i do about it? Thanks a lot.

**Comment by SNDima** [comment]
Just the same question.

**Comment by haskil37** [comment]
Sorry for my english

Becouse AvatarStoredWidth and AvatarStoredHeight in controller is more than width and height .preview-container in site.avatar.css
For example

```
AvatarStoredWidth = 200
AvatarStoredHeight = 200
/**/
.preview-container{
        width: 100px;  
        height: 100px; 
}
```

Then

```
img.Crop(top, left, img.Height - top - AvatarStoredHeight, img.Width - left - AvatarStoredWidth);
img.Crop(top, left, 100 - top - 200, 100 - left - 200);

```

Must 

```
width >= AvatarStoredWidth 
height >= AvatarStoredHeight 
```

**Comment by erdenemunkh** [comment]
I have same problem. I set AvatarStoredWidth = 300, AvatarStoredHeight = 300 but crop not working. How to solve this problem

**Comment by MiroJ** [comment]
The issue is most-likely caused by difference in the cropping area dimensions between AvatarController.cs and site.avatar.css. Make sure you search for all ToDo's and address them.
