### ISSUE TITLE
Upload Problem

### ISSUE THREAD

**Issue by mohsenhk** [MiroJ/AvatarUpload#7]
_Hi @MiroJ 
I'm using your sample project in my solution but have a problem after "Choose File",crop and click on "SAVEAVATAR" button. Could you help me? 
Thanks and Best Regards_

![problem](https://cloud.githubusercontent.com/assets/4437330/19092065/f51633f8-8a91-11e6-8f21-4d41966d7d5e.png)

> localhost:44300 says:
> 
> Unable to upload file.
> ERRORINFO: Value must be greater than or equal to 0.
> 
> Parameter name: bottom

**Comment by kiko81** [comment]
got the same error

**Comment by haskil37** [comment]
Problem in this code

```
img.Resize(width, height);
// ... crop the part the user selected, ...
img.Crop(top, left, img.Height - top - AvatarStoredHeight, img.Width - left - AvatarStoredWidth);
```

I had the same problem at such values:

```
private const int AvatarStoredWidth = 400; 
private const int AvatarStoredHeight = 400;
private const int AvatarScreenWidth = 600; 
```

If i crop height 420 and jcrop-tracker in bottom of image, after resize height became 419 and img.Height - top - AvatarStoredHeight is less than 0
You can do that 

```
img.Resize(width, height);
int bottom = img.Height - top - AvatarStoredHeight;
int right = img.Width - left - AvatarStoredWidth;
if (bottom < 0)
{
   top = top + bottom;
   bottom = 0;
}
img.Crop(top, left, bottom, right);
```

**Comment by mohsenhk** [comment]
Hi! I faced too many problems 😆 but i remember i solved this problem by replace

```
var top = Convert.ToInt32(t.Replace("-", "").Replace("px", ""));
var left = Convert.ToInt32(l.Replace("-", "").Replace("px", ""));
var height = Convert.ToInt32(h.Replace("-", "").Replace("px", ""));
var width = Convert.ToInt32(w.Replace("-", "").Replace("px", ""));
```

with

```
char[] delimiterChars = { '.' };
var top = Convert.ToInt32(t.Replace("-", "").Replace("px", "").Split(delimiterChars)[0]);
var left = Convert.ToInt32(l.Replace("-", "").Replace("px", "").Split(delimiterChars)[0]);
var height = Convert.ToInt32(h.Replace("-", "").Replace("px", "").Split(delimiterChars)[0]);
var width = Convert.ToInt32(w.Replace("-", "").Replace("px", "").Split(delimiterChars)[0]);
```

and
`img.Crop(top, left, img.Height - top - AvatarStoredHeight, img.Width - left - AvatarStoredWidth);`
with
`img.Crop(top, left, img.Height - top - AvatarStoredHeight + 1, img.Width - left - AvatarStoredWidth + 1);`
in _"AvatarController "_'s _"Save"_ function!

**Comment by mmushtaq94** [comment]
Hi , i have to face the same problem...
i try both of the solution provide above ..but it dosn't solve my problem ..
kindly , provide me appropriate solution ..
_Thanks and best Regards_

**Comment by MiroJ** [comment]
The issue is most-likely caused by difference in the cropping area dimensions between AvatarController.cs and site.avatar.css. Make sure you search for all ToDo's and address them.
