### ISSUE TITLE
Database Issue

### ISSUE THREAD

**Issue by jviseur** [MiroJ/AvatarUpload#9]
@MiroJ 

By default the project assumes you are using SQLServer 2012.  This can be overcome by replacing the existing connection string in web.config file with

&lt;add name="DefaultConnection" connectionString="Data Source=(localdb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\aspnet-test-AvatarUpload-20140512111401.mdf;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False" providerName="System.Data.SqlClient" /&gt;

**Comment by MiroJ** [comment]
Thank you, John!
I fixed the connection string.

**Comment by MiroJ** [comment]
Thank you, John!
I updated the connection string.
